DTC_INCLUDE += $(srctree)/../sm6375-modules/qcom/opensource/camera-kernel

include $(srctree)/$(src)/config/blair.mk

always-y	:= $(dtbo-y) $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo
